version: '2'
services:
  dashboard:
    container_name: dashboard
    build:
      context: .
      dockerfile: ./Dashboard/Dockerfile
    environment:
      - REACT_APP_OSTEP_DASH_HOST=$HOSTNAME
    depends_on:
      - 'osteppy'
      - 'lamp'
      - 'rapresenter'
      - 'github'
      - 'infrastructure'
    ports:
      - '8080:8080'
    restart: always
  osteppy:
    container_name: osteppy
    build: ./Osteppy
    env_file:
      - .dashboard.env
    ports:
      - '127.0.0.1:8000:8000'
    restart: always
  lamp:
    container_name: lamp
    build: ./Lamp
    ports:
      - '127.0.0.1:8001:8001'
    restart: always
  rapresenter:
    container_name: rapresenter
    build: ./RAPresenter
    ports:
      - '127.0.0.1:8002:8002'
    restart: always
  infrastructure:
    container_name: infrastructure
    build:
      context: .
      dockerfile: ./Infrastructure/Dockerfile
    ports:
      - '127.0.0.1:8003:8003'
    restart: always
  github:
    container_name: github
    build:
      context: .
      dockerfile: ./Github/Dockerfile
    ports:
      - '127.0.0.1:8004:8004'
    restart: always
