version: '2'
services:
  dashboard:
    container_name: dashboard
    build:
      context: .
      dockerfile: ./Dashboard/Dockerfile
    environment:
      - REACT_APP_OSTEP_DASH_HOST=$HOSTNAME
    depends_on:
      - 'lamp'
      - 'rapresenter'
      - 'github'
      - 'infrastructure'
    ports:
      - '80:80'
    restart: always
  lamp:
    container_name: lamp
    build: ./Lamp
    expose:
      - '80'
    restart: always
  rapresenter:
    container_name: rapresenter
    build: ./RAPresenter
    expose:
      - '80'
    restart: always
  infrastructure:
    container_name: infrastructure
    build:
      context: .
      dockerfile: ./Infrastructure/Dockerfile
    expose:
      - '80'
    restart: always
  github:
    container_name: github
    build:
      context: .
      dockerfile: ./Github/Dockerfile
    expose:
      - '80'
    restart: always
