version: '2'
services:
  dashboard:
    container_name: dashboard
    build: ./Dashboard
    depends_on:
     - "osteppy"
     - "lamp"
     - "rapresenter"
     - "db1042"
    #  - "infrastructure"
    ports:
     - "8080:3000"
  osteppy:
    container_name: osteppy
    build: ./Osteppy
    ports:
      - "8081:8080"
  lamp:
    container_name: lamp
    build: ./LAMP
    ports:
      - "8082:8080"
  rapresenter:
    container_name: rapresenter
    build: ./RAPresenter
    ports:
      - "8083:8083"
  db1042:
    container_name: db1042
    build: ./DB1042
    ports:
      - "8084:8084"
  # infrastructure:
  #   container_name: infrastructure
  #   build: ./Infrastructure
  #   env_file:
  #     - infrastructure.env
  #   ports:
  #     - "8085:3000"
  github:
    container_name: github
    build: ./Github
    env_file:
      - github.env
    ports:
      - "8086:4141"

