version: '2'
services:
  dashboard:
    container_name: dashboard
    build: ./Dashboard
    environment:
     - REACT_APP_OSTEP_DASH_HOST=$HOSTNAME
    depends_on:
     - "osteppy"
     - "lamp"
     - "rapresenter"
     - "db1042"
     - "github"
     - "infrastructure"
    ports:
     - "80:80"
    restart: always
  osteppy:
    container_name: osteppy
    build: ./Osteppy
    env_file:
      - .dashboard.env
    expose:
      - "80"
    restart: always
  lamp:
    container_name: lamp
    build: ./Lamp
    expose:
      - "80"
    restart: always
  rapresenter:
    container_name: rapresenter
    build: ./RAPresenter
    expose:
      - "80"
    restart: always
  db1042:
    container_name: db1042
    build: ./DB1042
    expose:
      - "80"
    restart: always
  infrastructure:
    container_name: infrastructure
    build: ./Infrastructure
    expose:
      - "80"
    restart: always
  github:
    container_name: github
    build: ./Github
    env_file:
      - .dashboard.env
    expose:
      - "80"
    restart: always

